### ISSUE TITLE
just black and a small flag

### ISSUE THREAD

**Issue by nkucza** [bendardenne/MMM-TomTomTraffic#1]
Hey,

i am currently trying your module and sadly it is just back and a small flag.
![tomtom](https://user-images.githubusercontent.com/37652990/65510566-8d356d80-ded5-11e9-9449-e66335668635.PNG)
did you encounter something like this?

Kind regard, Nils

**Comment by bendardenne** [comment]
There is a mistake in the example config in the README.

Try to move the `size` option into the `config` block. E.g.: 

 ```javascript
      module: "MMM-TomTomTraffic",
      position: "bottom_left",
      config: {
        location: [... , ... ],
        zoomLevel: 14,
        size: 500,
        tomtom: {
          apiToken: "...",
          thickness: 4,
        },
```
