### ISSUE TITLE
Nothing showing

### ISSUE THREAD

**Issue by sowhat621** [bendardenne/MMM-TomTomTraffic#2]
Hey there,
Ive installed the module, but nothing showing up. I am using all api products for my customer api of tomtom.
Why isnt it showing something?

{
        		module: "MMM-TomTomTraffic",
        		position: "left",
        		config: {
          		location: [50.190164, 11.789924],
          		zoomLevel: 6,
			size: 700,
          		tomtom: {
            		apiToken: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            		thickness: 8,
          			},
        			},

**Comment by bendardenne** [comment]
It's probably crashing because there is no mapbox section in your `config`. I've pushed a fix.
Either pull the latest changes, or add an empty mapbox entry in your config

```javascript
config = {
    tomtom: {
//  ...  your config
    }
    mapbox: {}
}

**Comment by sowhat621** [comment]
Now Its working, thanks!
