### ISSUE TITLE
Cant change layout with openmap

### ISSUE THREAD

**Issue by sowhat621** [bendardenne/MMM-TomTomTraffic#3]
Hey,

I've been trying to change the layout now, but Its not working/changing.
Could there be something wrong with this code in the MMM-TomTomTraffic.js?
`L.tileLayer("https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}"`

**Comment by bendardenne** [comment]
What do you mean with changing the layout?

**Comment by sowhat621** [comment]
Changing the style of the map in one of these ->
mapbox/streets-v11
mapbox/outdoors-v11
mapbox/light-v10
mapbox/dark-v10
mapbox/satellite-v9
mapbox/satellite-streets-v11
mapbox/navigation-preview-day-v4
mapbox/navigation-preview-night-v4
mapbox/navigation-guidance-day-v4
 mapbox/navigation-guidance-night-v4

Its always the same style like having none of these activated

**Comment by bendardenne** [comment]
In your config, specify the `mapId` option to the value of your choice: 

```javascript
    config: {
        location: [x, y],
        zoomLevel: z,
        size: 500,
        tomtom: {
       // ...
       },
        mapbox: {
          apiToken: "YOUR_MAPBOX_TOKEN",
          mapId: "mapbox/dark-v10"
        }
      }

**Comment by sowhat621** [comment]
https://api.mapbox.com/styles/v1/mapbox/light-v10/tiles/10/50.151961/11.748510?access_token=pk.eyXXXXXXXXXXX
this would be the link with all variables - but It says message: Not Found - and thats the reason I cant load up the style into the magic mirror.

**Comment by bendardenne** [comment]
The `{x}` and `{y}` will not be replaced with the latitude and longitude. They are replaced by leaflet with the tile coordinates for the relevant region.

Basically, at zoom level 0, there is only one tile (x = 0, y = 0). At every zoom level, the number of columns (x) and rows (y) is doubled. At zoom level 1, there are four tiles (x = 0 or 1, y  = 0 or 1). At zoom level 2, there are 16 (4x4), etc... For more details, see https://en.wikipedia.org/wiki/Tiled_web_map

A correct URL would be for instance: 

https://api.mapbox.com/styles/v1/mapbox/light-v10/tiles/10/545/346?access_token=your_key

But leaflet will do that for you. Normally, you should just be able to specify the mapId in the config.

Note that you should include the "pk.ey" in your API token in the config.

**Comment by sowhat621** [comment]
Ok, I've found the error, 
I've missed to close the tomtom { config setting. Now its working!

**Comment by sowhat621** [comment]
-
