### ISSUE TITLE
remove the shadow and reduce the size of the displayed module

### ISSUE THREAD

**Issue by ghost** [bendardenne/MMM-TomTomTraffic#4]
Hello,
how to remove the shadow under the circle?
how to reduce the size of the displayed module? Which code to write and where? In the config.js or custom.css?
Thank you for your help.

**Comment by ghost** [comment]
[url=https://zupimages.net/viewer.php?id=20/26/gtbg.png][img]https://zupimages.net/up/20/26/gtbg.png[/img][/url]

**Comment by ghost** [comment]
https://zupimages.net/viewer.php?id=20/26/gtbg.png

**Comment by bendardenne** [comment]
You can tweak the `size` parameter. It's the diameter of the circle, in pixels.

To remove the reflection, remove or comment out the  `-webkit-box-reflect` line in the CSS.

**Comment by ghost** [comment]
thnak's a lot for the size, 
where to find `-webkit-box-reflect` line, it's not in MMM-TomTomTraffic.css ? And what comment ?

**Comment by bendardenne** [comment]
Line 3 in  MMM-TomTomTraffic.css.
Just delete the line.

**Comment by ghost** [comment]
SUPER ! Thank for Aeverything !
