### ISSUE TITLE
HOW to delete the MapBox and OpenstreeMap displayed on my MM 

### ISSUE THREAD

**Issue by ghost** [bendardenne/MMM-TomTomTraffic#5]
Hello,
HOW to delete the MapBox and OpenstreeMap displayed on my MM at the bottom right of the map, 
Thank you.

**Comment by bendardenne** [comment]
Hello,

In the JS file you could remove the attribution container. Note that this would most likely be a violation of the MapBox and OSM terms of use.

**Comment by ghost** [comment]
Ok, thanks, I don't do this, so.
