### ISSUE TITLE
Increase text size of place names

### ISSUE THREAD

**Issue by robertybob** [bendardenne/MMM-TomTomTraffic#6]
Hi, I was just wondering if there was any way of increasing the size of the text (i.e. the road / town names) as I'm having to use zoom level 13 to show the local roads I need, however it's pretty much impossible to read the road names and names of the surrounding villages.

**Comment by bendardenne** [comment]
This will depend on the mapbox style that you use (this is configurable). I use one without any labels at all, myself (well, used, since my mirror died and I'm not using this anymore).

You can create your own style in Mapbox Studio, and in there it's possible to change the sizes of text.
It's not the easiest tool to use (mostly because it allows you to tweak many, many things), but it's possible and knowing your zoom level upfront makes things easier. 
Once your style is defined, you'll need to configure the `mapId` setting of the module with the right reference.

**Comment by robertybob** [comment]
> 
> 
> This will depend on the mapbox style that you use (this is configurable). I use one without any labels at all, myself (well, used, since my mirror died and I'm not using this anymore).
> 
> You can create your own style in Mapbox Studio, and in there it's possible to change the sizes of text.
> It's not the easiest tool to use (mostly because it allows you to tweak many, many things), but it's possible and knowing your zoom level upfront makes things easier.
> Once your style is defined, you'll need to configure the `mapId` setting of the module with the right reference.

Ah brilliant, I've just played around with it and got it working fine. Thank you so much! Sorry to hear about your mirror though, I assume this module is no longer maintained since you don't have a MagicMirror anymore?

**Comment by bendardenne** [comment]
> I assume this module is no longer maintained since you don't have a MagicMirror anymore?

Probably not. I might fix minor issues and answer questions. I'll gladly pass ownership to anyone who uses this and wants to maintain it, though.

**Comment by robertybob** [comment]
> 
> 
> > I assume this module is no longer maintained since you don't have a MagicMirror anymore?
> 
> Probably not. I might fix minor issues and answer questions. I'll gladly pass ownership to anyone who uses this and wants to maintain it, though.

Ah that's a shame, it's the only traffic-related module that actually works for me lol. While I've got your attention, I can't see anywhere which says why the map is within a circle unlike similar modules (albeit ones that don't work for me) which have the image in a square. Is this something I can change?

**Comment by bendardenne** [comment]
That's just because I liked it that way :).
If you want it square, you'll need to play with the CSS. Start by removing the map's border-radius. That might be enough.
It think the attribution string will still be curved, and probably misplaced. For that you'll need some changes in the JS.

**Comment by robertybob** [comment]
@bendardenne Yep getting rid of the radius sorted it! Out of interest, how often does the map/traffic info update? There's no option to specify a refresh interval in the settings, so I assume it's done automatically by TomTom and the image on the MagicMirror will update accordingly?

**Comment by bendardenne** [comment]
@robertybob the map will re-query the data from TomTom every 10 minutes. 

I don't remember how often TomTom themselves update their data. If you want to refresh more often, also check how many queries per day the free API key allows you to make (or geta a paid one).
