### ISSUE TITLE
Automatically Cleread after 10 minutes (re-draw)

### ISSUE THREAD

**Issue by emrahaslan** [bendardenne/MMM-TomTomTraffic#7]
It's works with Tom Tom and MapBox ApiKey, but when I wait up to 20 minutes, all the green lines and traffic ticks has removed.

![image](https://user-images.githubusercontent.com/54321532/92948992-fb669d80-f462-11ea-8e7f-ed0fe526dcb6.png)

**Comment by emrahaslan** [comment]
here is my config 


	{
			module: "MMM-TomTomTraffic",
			header: "YOGUNLUK HARİTASI",
			position: "bottom_left",
			config: {
			  location: [41.02905572019998,29.04429195055218],
			  size: 320,
			  zoomLevel: 12,
			  tomtom: {
				apiToken: "tom tom token",
				thickness: 2,
			  },
			  mapbox: {
				apiToken: "pk.mapbpx token",
				mapId: "mapbox/light-v10"
			  }
			}
		  }

**Comment by bendardenne** [comment]
Is there anything in the browser console (f12) / npm output?
