### ISSUE TITLE
 email received from TomTom : Deprecation Notice – Traffic Incidents Details v4

### ISSUE THREAD

**Issue by ghost** [bendardenne/MMM-TomTomTraffic#9]
Hello,
I use the MM-TomTom Traffic module
I received this email below from tomtom yesterday, and I am having trouble understanding this email.
Will this change something for the module, is there an update to do and which one ?

"We’d like to notify you about the deprecation of Traffic Incidents Details API v4, part of the Traffic API family. The deprecation will be effective as of 04/13/2021 under the TomTom deprecation policy. The planned withdrawal date is in one year later, on 04/13/2022. 									 									Why is this happening? 									 									We’re constantly making improvements in our products based on  feedback from the users. In this update specifically, we eliminated  superfluous steps, simplifying the overall usage. 									 									Here’s the changes to expect with version 5 of the Traffic Incidents Details API:
--
 
  | Only EPSG4326 coordinate system is supported;
 
  | Only JSON format is supported;
 
  | Flexibility to work with selected attributes only:
 
  | Bandwidth optimization (no over- and under-fetching problems)
 
  | Adding new attributes is always backward compatible and does not affect existing clients
 
  | Support for event codes (Alert-C);
 
  | No relation to styles or visualization:
 
  | - No shifted geometry provided
 
  | - No support for clusters
 
  | Different bounding-box limitation
 
  | Clearer end-point parameter names"

This is the link of TomTom Traffic API : https://developer.tomtom.com/traffic-api/traffic-api-documentation-traffic-incidents/incident-details-v4?utm_source=oneoff&utm_medium=email&utm_campaign=dev_all_trafficincidentdetailsdeprecation_202104_oo_news

**Comment by bendardenne** [comment]
Hi,

This API is for getting details about traffic incidents (accidents, road closures, etc) which the module does not use. The module only calls the "traffic flow" API, which is different.

It should keep working after this deprecation.

**Comment by ghost** [comment]
Thank you
